---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Developer:
    - Github:
        - abbr: GH
          href: https://github.com/

- Social:
    - facebook:
        - abbr: RE
          href: https://web.facebook.com/

- Entertainment:
    - YouTube:
        - abbr: YT
          href: https://www.youtube.com/@Elpp021
